name: Release

on:
  create:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: darwin
          EXTRA_FILES: "LICENSE"
