name: Release

on:
  create:
    tags:
      - v*

jobs:
  build:
    name: Build
    runs-on: [self-hosted, macOS, X64]
    steps:
      - uses: actions/checkout@v2
      - run: ./build.sh
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/windows/win64-auth.exe
          asset_name: win64-auth.exe
          asset_content_type: application/vnd.microsoft.portable-executable
